// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:suito_web/env/env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: Env.kFirebaseWebApiKey,
    appId: Env.kFirebaseWebAppId,
    messagingSenderId: Env.kFirebaseMessagingSenderId,
    projectId: Env.kFirebaseProjectId,
    authDomain: Env.kFirebaseAuthDomain,
    storageBucket: Env.kFirebaseStorageBucket,
  );
}
