-- Local-only seed. `supabase db reset` runs this after the migrations; it is
-- never applied by `supabase db push`.
--
-- Intentionally empty.
--
-- This file used to force app_config's version to match mobile/pubspec.yaml,
-- because the forced-update check compared for exact equality and the '1.0.0'
-- default therefore covered the local app in a dialog that could not be
-- dismissed. 0009 turned that check into a semantic "older than
-- min_required_version" test, so the default is now below every build and the
-- local stack is usable with no seeding at all.
--
-- Add rows here if some future feature needs local fixtures.
