[server]
host = ""
port = "8009"
ver = "1.0.0"

[db]
type = "mysql"
host = ""
port = 3306
user = ""
passwd = ""
sslmode = "false"
database = ""
max_idle_conns = 2
max_open_conns = 100
logmode = true

[log]
log = "stdout"
err_log = "stderr"
activity_log = "stdout"
# debug|info|warn|error|dpanic|panic|fatal
level = "debug"