version: '3'
services:
  suito:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: suito
    container_name: suito
    environment:
      DB_HOST: suito-db
      DB_PORT: 3306
      # REDIS_SERVER: suito-redis:6379
      GIT_REVISION: ${GIT_REVISION:-develop}
      GIT_BRANCH: ${GIT_BRANCH:-develop}
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    volumes:
      - ./backend:/backend
      - ./ddl:/ddl:ro
      - ./certs:/var/www/certs
    depends_on:
      db:
        condition: service_healthy
      # redis:
      #   condition: service_started
    env_file: .env.suito
  suito-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: suito-web
    container_name: suito-web
    ports:
      - "1200:80"
    volumes:
      - ./web:/web
  db:
    container_name: suito-db
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3346:3306"
    cap_add:
      - SYS_NICE
