version: '3'
services:
  suito:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: suito
    container_name: suito
    environment:
      DB_HOST: suito-db
      DB_PORT: 3306
      # REDIS_SERVER: suito-redis:6379
      GIT_REVISION: ${GIT_REVISION:-develop}
      GIT_BRANCH: ${GIT_BRANCH:-develop}
    volumes:
      - ./backend:/backend
      - ./ddl:/ddl:ro
    depends_on:
      db:
        condition: service_healthy
      # redis:
      #   condition: service_started
    env_file: .env.suito
    healthcheck:
      test: ["CMD", "curl" ,"-f", "localhost:8009/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    container_name: suito-db
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3346:3306"
    cap_add:
      - SYS_NICE
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/html:/var/www/html
      - /etc/lego:/etc/lego
      - ./web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/build/web:/var/www/web
    depends_on:
      - suito
