version: '3'
services:
  suito-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: suito-web
    container_name: suito-web
    ports:
      - "1200:80"
    volumes:
      - ./web/build/web:/usr/share/nginx/html
