[config]
skip_core_tasks = true

[env]
GIT_HASH = { script = ["git rev-parse --short HEAD"] }

[tasks.install]
script = '''
go install github.com/swaggo/swag/cmd/swag@v1.8.4
go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.15.2
go install github.com/mfridman/tparse@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
'''


[tasks.format]
script = "go fmt ./..."

[tasks.lint]
script = "golangci-lint run --tests  ./..."

[tasks.swag]
script = """
swag init --parseDependency --requiredByDefault=true
# covert to V3 format
curl -X 'POST' \
  'https://converter.swagger.io/api/convert' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '@docs/swagger.json' | jq . > docs/tmp_v3_swagger.json
curl -X 'POST' \
  'https://converter.swagger.io/api/convert' \
  -H 'accept: application/yaml' \
  -H 'Content-Type: application/yaml' \
  -d '@docs/swagger.json' \
  -o 'docs/tmp_v3_swagger.yaml'
mv docs/tmp_v3_swagger.json docs/swagger.json
mv docs/tmp_v3_swagger.yaml docs/swagger.yaml
"""

[tasks.build]
dependencies = ["format"]
script = """
GOOS=linux GOARCH=amd64 go build -ldflags "-X env.CommitHash=${GIT_HASH}" -o ./suito
"""

[tasks.build-production]
dependencies = ["format"]
script = """
GOOS=linux GOARCH=amd64 go build -tags release -ldflags "-X env.CommitHash=${GIT_HASH}" -o ./suito
"""

[tasks.run]
script = """
go build -o ./suito
./suito run --config ./config/config.debug.toml
"""

[tasks.test]
dependencies = ["format", "lint"]
script = """
#!/usr/bin/env bash
set -o pipefail
go test --short $1 -ldflags "-X github.com/wakamenod/suito/env.TEST=test" -count=1 -p=1 -cover -coverprofile=cover.out ./... -json | tparse -smallscreen $2
"""

[tasks.test-github]
dependencies = ["format"]
script = """
#!/usr/bin/env bash
set -o pipefail
go test --short $1 -count=1 -p=1 -cover -coverprofile=cover.out ./... -json | tparse -smallscreen $2
"""
