((nil . ((projectile-project-compilation-dir . "./mobile")
         (projectile-project-test-cmd . "just test")
         (projectile-project-compilation-cmd . "just lint")
         (projectile-project-run-cmd . "just run")
         (projectile-project-package-cmd . "just clean")
         )))
