[config]
skip_core_tasks = true

[tasks.clean]
script = '''
fvm flutter clean
'''

[tasks.install]
script = '''
fvm flutter pub get
'''

[tasks.fvm-install]
script = '''
fvm install
'''

[tasks.format]
script = '''
fvm dart format lib test
'''

[tasks.slang]
script = '''
fvm dart run slang watch
'''

[tasks.run]
script = '''
# fvm flutter run --flavor dev -t lib/main-dev.dart
# fvm flutter run --flavor dev -t lib/main.dart
fvm flutter run --dart-define-from-file=dart_defines/dev.json
'''

[tasks.build_runner_watch]
script = '''
fvm flutter pub run build_runner watch --delete-conflicting-outputs
'''

[tasks.run-prod]
script = '''
# fvm flutter run --release  --flavor prod -t lib/main-prod.dart
fvm flutter run --dart-define-from-file=dart_defines/prod.json
'''

[tasks.test]
script = '''
# vscodeのflutter coverageはlcovファイル内に同じソースファイル(SF)が復数回出現した場合に合算されない
# lcov-result-mergerを使ってマージすることにした
fvm flutter test --coverage --coverage-path="coverage/source_lcov.info"
./node_modules/.bin/lcov-result-merger ./coverage/source_lcov.info ./coverage/lcov.info
rm coverage/source_lcov.info
# fvm flutter test lib --machine > machine.log || echo 'Tests failed'
# flutter pub global run dart_dot_reporter machine.log --show-message
'''

[tasks.test-logic]
script = '''
fvm flutter test --exclude-tags golden --coverage --coverage-path="coverage/source_lcov.info"
./node_modules/.bin/lcov-result-merger ./coverage/source_lcov.info ./coverage/lcov.info
rm coverage/source_lcov.info
'''

[tasks.ci-test]
script = '''
fvm flutter test
'''

[tasks.lint]
dependencies = ["format"]
script = '''
# fvm dart fix --apply
fvm flutter analyze
'''

[tasks.freeze]
script = '''
fvm flutter pub run build_runner build --delete-conflicting-outputs
'''

[tasks.build-appbundle]
script = '''
fvm flutter build appbundle --dart-define-from-file=dart_defines/prod.json --obfuscate --split-debug-info=obfuscate/android
'''

[tasks.icon]
script = '''
fvm flutter pub run flutter_launcher_icons:main
'''

[tasks.api-generate]
script = '''
  rm -fr ./openapi/
  ./bin/openapi-generator-cli.jar generate \
  -i ../backend/docs/swagger.yaml \
  -g dart-dio \
  -o openapi/client/ \
  --additional-properties=useEnumExtension=true
cd ./openapi/client
flutter pub get
flutter packages pub run build_runner build --delete-conflicting-outputs
'''

[tasks.update-goldens]
script = '''
fvm flutter test --update-goldens
'''