[config]
skip_core_tasks = true

[tasks.clean]
script = '''
fvm flutter clean
'''

[tasks.install]
script = '''
fvm flutter pub get
'''

[tasks.fvm-install]
script = '''
fvm install
'''

[tasks.format]
script = '''
fvm dart format lib
'''

[tasks.run]
script = '''
# fvm flutter run --flavor dev -t lib/main-dev.dart
# fvm flutter run --flavor dev -t lib/main.dart
fvm flutter run --dart-define-from-file=dart_defines/dev.json
'''

[tasks.build_runner_watch]
script = '''
fvm flutter pub run build_runner watch --delete-conflicting-outputs
'''

[tasks.run-prod]
script = '''
# fvm flutter run --release  --flavor prod -t lib/main-prod.dart
fvm flutter run --dart-define-from-file=dart_defines/prod.json
'''

[tasks.test]
script = '''
fvm flutter test lib
# fvm flutter test lib --machine > machine.log || echo 'Tests failed'
# flutter pub global run dart_dot_reporter machine.log --show-message
'''

[tasks.lint]
dependencies = ["format"]
script = '''
fvm flutter analyze
'''

[tasks.freeze]
script = '''
fvm flutter pub run build_runner build --delete-conflicting-outputs
'''

[tasks.build-appbundle]
script = '''
fvm flutter build appbundle
'''

[tasks.api-generate]
script = '''
  rm -fr ./openapi/
  ./bin/openapi-generator-cli.jar generate \
  -i ../backend/docs/swagger.yaml \
  -g dart-dio \
  -o openapi/client/ \
  --additional-properties=useEnumExtension=true
cd ./openapi/client
flutter pub get
flutter packages pub run build_runner build --delete-conflicting-outputs
'''