name: suito
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cupertino_icons: ^1.0.2
  firebase_ui_auth: 1.3.0
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  dio: ^5.1.2
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: 0.3.4
  riverpod_lint: 1.3.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.2

flutter:
  uses-material-design: true
