name: suito
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  # sdk: ">=2.19.6 <3.0.0"
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cupertino_icons: ^1.0.2
  firebase_ui_auth: 1.3.0
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  dio: ^4.0.1
  riverpod_annotation: ^2.1.1
  envied: ^0.3.0+3
  rxdart: ^0.27.7
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  openapi:
    path: ./openapi/client
  dropdown_button2: ^2.1.3
  mocktail: ^0.3.0
  formz: ^0.6.0
  intl: ^0.18.0
  slang: ^3.18.1
  slang_flutter: ^3.18.0

dev_dependencies:
  custom_lint: 0.3.4
  riverpod_lint: 1.3.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.2
  envied_generator: ^0.3.0+3
  freezed: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
