openapi: 3.0.1
info:
  title: suito
  contact: {}
  version: "1.0"
servers:
- url: //localhost:8009/api/v1
paths:
  /expense/categories:
    get:
      tags:
      - suito.expense
      summary: List expense categories
      description: 購入カテゴリー一覧を返却します.
      operationId: listExpenseCategories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListExpenseCategoriesRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
  /expense/locations:
    get:
      tags:
      - suito.expense
      summary: List expense locations
      description: 購入場所ー一覧を返却します.
      operationId: listExpenseLocations
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListExpenseLocationsRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
  /ping:
    get:
      tags:
      - suito.default
      summary: Ping
      description: Ping
      operationId: ping
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
  /transactions:
    get:
      tags:
      - suito.transactions
      summary: List transactions
      description: List transactions.
      operationId: listTransactions
      parameters:
      - name: yearMonth
        in: query
        description: yearMonth
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTransactionsRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
  /transactions/months:
    get:
      tags:
      - suito.transactions
      summary: List transaction months
      description: トランザクションが発生した月(YYYY-MM)の一覧を取得します.
      operationId: transactionMonths
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionMonthsRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
components:
  schemas:
    ListExpenseCategoriesRes:
      required:
      - expenseCategories
      type: object
      properties:
        expenseCategories:
          type: array
          items:
            $ref: '#/components/schemas/model.ExpenseCategory'
    ListExpenseLocationsRes:
      required:
      - expenseLocations
      type: object
      properties:
        expenseLocations:
          type: array
          items:
            $ref: '#/components/schemas/model.ExpenseLocation'
    ListTransactionsRes:
      required:
      - transactions
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    SuitoError:
      type: object
      properties:
        ErrCode:
          type: string
        message:
          type: string
    Transaction:
      required:
      - amount
      - id
      - localDate
      - title
      - type
      type: object
      properties:
        amount:
          type: integer
        id:
          type: string
        localDate:
          type: string
        title:
          type: string
        type:
          type: integer
    TransactionMonthsRes:
      required:
      - yearMonths
      type: object
      properties:
        yearMonths:
          type: array
          items:
            type: string
    model.ExpenseCategory:
      required:
      - id
      - name
      - uid
      type: object
      properties:
        createdAt:
          type: string
        id:
          type: string
        name:
          type: string
        uid:
          type: string
        updatedAt:
          type: string
    model.ExpenseLocation:
      required:
      - id
      - name
      - uid
      type: object
      properties:
        createdAt:
          type: string
        id:
          type: string
        name:
          type: string
        uid:
          type: string
        updatedAt:
          type: string
