openapi: 3.0.1
info:
  title: suito
  contact: {}
  version: "1.0"
servers:
- url: //localhost:8009/api/v1
paths:
  /ping:
    get:
      tags:
      - suito.default
      summary: Ping
      description: Ping
      operationId: ping
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
  /transactions:
    get:
      tags:
      - suito.transactions
      summary: List transactions
      description: List transactions.
      operationId: listTransactions
      parameters:
      - name: yearMonth
        in: query
        description: yearMonth
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTransactionsRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorRes'
components:
  schemas:
    APIErrorInfo:
      required:
      - code
      - data
      - message
      type: object
      properties:
        code:
          type: string
        data:
          type: string
        message:
          type: string
    APIErrorRes:
      required:
      - errorInfo
      type: object
      properties:
        errorInfo:
          $ref: '#/components/schemas/APIErrorInfo'
    ListTransactionsRes:
      required:
      - transactions
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      required:
      - amount
      - id
      - localDate
      - title
      - type
      type: object
      properties:
        amount:
          type: integer
        id:
          type: string
        localDate:
          type: string
        title:
          type: string
        type:
          type: integer
