openapi: 3.0.1
info:
  title: suito
  contact: {}
  version: "1.0"
servers:
- url: //localhost:8009/api/v1
paths:
  /expense:
    post:
      tags:
      - suito.expense
      summary: Register expense
      description: 支出情報を登録します
      operationId: registerExpense
      requestBody:
        description: register expense req
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterExpenseReq'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterExpenseRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
      x-codegen-request-body-name: request
  /expense/categories:
    get:
      tags:
      - suito.expense
      summary: List expense categories
      description: 購入カテゴリー一覧を返却します.
      operationId: listExpenseCategories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListExpenseCategoriesRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
  /expense/detail:
    post:
      tags:
      - suito.expense
      summary: Get expense detail
      description: 購入詳細情報を取得します.
      operationId: expenseDetail
      requestBody:
        description: expense detail req
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseDetailReq'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseDetailRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
      x-codegen-request-body-name: request
  /expense/locations:
    get:
      tags:
      - suito.expense
      summary: List expense locations
      description: 購入場所ー一覧を返却します.
      operationId: listExpenseLocations
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListExpenseLocationsRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
  /income:
    post:
      tags:
      - suito.income
      summary: Register income
      description: 収入情報を登録します
      operationId: registerIncome
      requestBody:
        description: register income req
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterIncomeReq'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterIncomeRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
      x-codegen-request-body-name: request
  /income/detail:
    post:
      tags:
      - suito.income
      summary: Get income detail
      description: 収入詳細情報を取得します.
      operationId: incomeDetail
      requestBody:
        description: income detail req
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncomeDetailReq'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomeDetailRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
      x-codegen-request-body-name: request
  /ping:
    get:
      tags:
      - suito.default
      summary: Ping
      description: Ping
      operationId: ping
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
  /transactions:
    get:
      tags:
      - suito.transactions
      summary: List transactions
      description: List transactions.
      operationId: listTransactions
      parameters:
      - name: yearMonth
        in: query
        description: yearMonth
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTransactionsRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
  /transactions/months:
    get:
      tags:
      - suito.transactions
      summary: List transaction months
      description: トランザクションが発生した月(YYYY-MM)の一覧を取得します.
      operationId: transactionMonths
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionMonthsRes'
        500:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuitoError'
components:
  schemas:
    ExpenseDetailReq:
      required:
      - id
      type: object
      properties:
        id:
          type: string
    ExpenseDetailRes:
      required:
      - expense
      type: object
      properties:
        expense:
          $ref: '#/components/schemas/model.Expense'
    IncomeDetailReq:
      required:
      - id
      type: object
      properties:
        id:
          type: string
    IncomeDetailRes:
      required:
      - income
      type: object
      properties:
        income:
          $ref: '#/components/schemas/model.Income'
    ListExpenseCategoriesRes:
      required:
      - expenseCategories
      type: object
      properties:
        expenseCategories:
          type: array
          items:
            $ref: '#/components/schemas/model.ExpenseCategory'
    ListExpenseLocationsRes:
      required:
      - expenseLocations
      type: object
      properties:
        expenseLocations:
          type: array
          items:
            $ref: '#/components/schemas/model.ExpenseLocation'
    ListTransactionsRes:
      required:
      - transactions
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    RegisterExpenseReq:
      required:
      - category
      - expense
      - location
      type: object
      properties:
        category:
          type: string
        expense:
          $ref: '#/components/schemas/model.Expense'
        location:
          type: string
    RegisterExpenseRes:
      required:
      - newExpense
      type: object
      properties:
        newExpense:
          $ref: '#/components/schemas/model.Expense'
    RegisterIncomeReq:
      required:
      - income
      type: object
      properties:
        income:
          $ref: '#/components/schemas/model.Income'
    RegisterIncomeRes:
      required:
      - newIncome
      type: object
      properties:
        newIncome:
          $ref: '#/components/schemas/model.Income'
    SuitoError:
      type: object
      properties:
        ErrCode:
          type: string
        message:
          type: string
    Transaction:
      required:
      - amount
      - id
      - localDate
      - title
      - type
      type: object
      properties:
        amount:
          type: integer
        id:
          type: string
        localDate:
          type: string
        title:
          type: string
        type:
          type: integer
    TransactionMonthsRes:
      required:
      - yearMonths
      type: object
      properties:
        yearMonths:
          type: array
          items:
            type: string
    model.Expense:
      required:
      - amount
      - expense_category_id
      - expense_location_id
      - id
      - local_date
      - memo
      - title
      type: object
      properties:
        amount:
          type: integer
        expense_category_id:
          type: string
        expense_location_id:
          type: string
        id:
          type: string
        local_date:
          type: string
        memo:
          type: string
        title:
          type: string
    model.ExpenseCategory:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    model.ExpenseLocation:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    model.Income:
      required:
      - amount
      - id
      - local_date
      - memo
      - title
      type: object
      properties:
        amount:
          type: integer
        id:
          type: string
        local_date:
          type: string
        memo:
          type: string
        title:
          type: string
