name: Suito Mobile CI

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "mobile/**"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create configuration files
        run: |
          echo "${{ secrets.ENV_DART }}" | base64 --decode > mobile/lib/env/env.g.dart
          echo "${{ secrets.IOS_RUNNER_GOOGLESERVICE_INFO_PLIST }}" | base64 --decode > mobile/ios/Runner/GoogleService-Info.plist
          echo "${{ secrets.IOS_FIREBASE_APP_ID_FILE_JSON }}" | base64 --decode > mobile/ios/firebase_app_id_file.json
          echo "${{ secrets.MACOS_RUNNER_GOOGLESERVICE_INFO_PLIST }}" | base64 --decode > mobile/macos/Runner/GoogleService-Info.plist
          echo "${{ secrets.MACOS_FIREBASE_APP_ID_FILE_JSON }}" | base64 --decode > mobile/macos/firebase_app_id_file.json

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: install fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up cargo-make
        uses: davidB/rust-cargo-make@v1
        with:
          version: "0.35.0"

      - name: setup flutter
        run: cd mobile && cargo make fvm-install

      - name: Flutter pub get
        run: cd mobile && cargo make install

      - name: Lint
        run: cd mobile && cargo make lint

      - name: Test
        run: cd mobile && cargo make ci-test
