name: Suito Backend Lint
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "backend/**"
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: backend/
          version: v2.13.2
          args: --timeout 3m --verbose
