name: Suito Backend Lint
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "backend/**"
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: backend/
          github-token: ${{ github.token }}
          skip-go-installation: true
          args: --timeout 3m --verbose
          version: v1.52.2
