name: CI suito

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create configuration files
        run: |
          echo "${{ secrets.LIB_FIREBASE_OPTIONS }}" | base64 --decode > lib/firebase_options.dart
          echo "${{ secrets.IOS_RUNNER_GOOGLESERVICE_INFO_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo "${{ secrets.IOS_FIREBASE_APP_ID_FILE_JSON }}" | base64 --decode > ios/firebase_app_id_file.json
          echo "${{ secrets.MACOS_RUNNER_GOOGLESERVICE_INFO_PLIST }}" | base64 --decode > macos/Runner/GoogleService-Info.plist
          echo "${{ secrets.MACOS_FIREBASE_APP_ID_FILE_JSON }}" | base64 --decode > macos/firebase_app_id_file.json

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: install fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up cargo-make
        uses: davidB/rust-cargo-make@v1
        with:
          version: "0.35.0"

      - name: setup flutter
        run: cargo make fvm-install

      - name: Flutter pub get
        run: cargo make install

      - name: Lint
        run: cargo make lint

      - name: Test
        run: cargo make test
