_default:
    @just --list

clean:
    fvm flutter clean

install:
    fvm flutter pub get

fvm-install:
    fvm install

format:
    fvm dart format lib test

build:
    fvm flutter build web
    tar -czvf build.tar.gz build

lint: format
    fvm flutter analyze

build_runner_watch:
    fvm flutter pub run build_runner watch --delete-conflicting-outputs

slang:
    fvm dart run slang watch
