name: suito_web
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: 2.3.6
  go_router: 7.1.1
  equatable: 2.0.5
  firebase_core: 2.13.0
  firebase_auth: 4.6.1
  firebase_ui_auth: 1.4.1
  envied: ^0.3.0+3
  slang: ^3.18.1
  slang_flutter: ^3.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
